apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx #Nome do pod
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
  dnsPolicy: ClusterFirst #A forma que kubernetes vai trabalhar para podermos acessar este pod atraves de um dns
  restartPolicy: Always
status: {}
