apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels: #Service busca pela labels e pelo app com valor service-demo-app atraves do selector
    app: service-demo-app
  name: service-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-demo-app
    spec:
      containers:
        - image: nginx:alpine
          name: service-demo-app
          resources: {}
status: {}
