apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  tls:
    - hosts:
        - whoami.devstore.info #Associar ssl ao ingress
      secretName: whoami-tls #nome da secret do certificado
  rules:
    - host: whoami.devstore.info
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-multipleports
                port:
                  number: 80
