apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-load-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-load-test #nome do deployment que ele busca no caso eh o hpa-load-test do arquivo load-test-yaml, em metadata => name
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 #Na media tem que estar abaixo de 50%, se ultrapassar vai acrescenter um novo pod
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 #Na media tem que estar abaixo de 70%, se ultrapassar vai acrescenter um novo pod
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30 #Depois que removeu um pod aguarda 30 segundos para ver as metricas novamente
      policies:
        - type: Percent
          value: 50 # vai diminuir de 50% a cada 30 segundos
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30 #Depois que adicionou um pod aguarda 30 segundos para ver as metricas novamente
      policies:
        - type: Percent
          value: 50 # vai aumentar em 50% a cada 30 segundos
          periodSeconds: 30
